Repository samtools/htsjdk, pull requests merged in 2018-10, with the labels that each got.

#1199 BetaIntegerCodecTest and bugfixes
  src/main/java/htsjdk/samtools/cram/encoding/BetaIntegerCodec.java
  src/test/java/htsjdk/samtools/cram/encoding/BetaIntegerCodecTest.java
Labels: bug, cram

#1194 Adding support for 0-length B arrays in SAM files to conform to 1.6 spec
  build.gradle
  src/main/java/htsjdk/samtools/SAMLineParser.java
  src/main/java/htsjdk/samtools/SAMRecord.java
  src/main/java/htsjdk/samtools/TextTagCodec.java
  src/test/java/htsjdk/samtools/SAMRecordUnitTest.java
  src/test/java/htsjdk/samtools/SAMTextReaderTest.java
  src/test/java/htsjdk/samtools/SAMTextWriterTest.java
  src/test/java/htsjdk/samtools/TextTagCodecTest.java
  src/test/java/htsjdk/tribble/TestUtils.java
  src/test/java/htsjdk/utils/TestNGUtils.java
  src/test/java/htsjdk/utils/TestNGUtilsTest.java
  src/test/resources/htsjdk/samtools/one-contig.fasta
  src/test/resources/htsjdk/samtools/one-contig.fasta.fai
Labels: Waiting for Review

#1069 MergeSamFiles accept SO:UNKNOWN
  src/main/java/htsjdk/samtools/SAMFileHeader.java
  src/main/java/htsjdk/samtools/SAMTextHeaderCodec.java
  src/test/java/htsjdk/samtools/SAMFileHeaderTest.java
  src/test/java/htsjdk/samtools/ValidateSamFileTest.java
Labels: 0 - Backlog
